return {
  {
    "karb94/neoscroll.nvim",
    event = "WinScrolled",
    opts = {
      hide_cursor = true,
      stop_eof = true,
      cursor_scrolls_alone = false,
      easing = "quadratic",
      respect_scrolloff = true,
    },
  },
  {
    "sphamba/smear-cursor.nvim",
    lazy = false,
    opts = {
      smear_between_buffers = true,
      smear_between_neighbor_lines = true,
      min_horizontal_distance_smear = 2,
      min_vertical_distance_smear = 2,
      scroll_buffer_space = true,
      smear_insert_mode = false,
      legacy_computing_symbols_support = false,
      transparent_bg_fallback_color = "#1f2335",
      anticipation = 0.08,
      stiffness = 0.42,
      trailing_stiffness = 0.3,
      damping = 0.96,
      distance_stop_animating = 0.35,
      stiffness_insert_mode = 0.55,
      trailing_stiffness_insert_mode = 0.4,
      damping_insert_mode = 0.97,
      hide_target_hack = true,
      never_draw_over_target = true,
    },
  },
}
